AllCops:
  TargetRubyVersion: 3.2

require:
  - rubocop-rspec
  - rubocop-rake

##
# LAYOUT COPS
##

Layout:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space
  SpaceBeforeBlockParameters: no_space
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

##
# STYLE COPS
##

Style:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/SpecialGlobalVars:
  Enabled: true
  EnforcedStyle: use_english_names

##
# NAMING COPS
##

Naming/BlockForwarding: # new in 1.24
  Enabled: false
Naming/MethodParameterName:
  Enabled: false

##
# SECURITY COPS
##

Security/CompoundHash: # new in 1.28
  Enabled: true
Security/IoMethods: # new in 1.22
  Enabled: true

##
# LINT COPS
##

Lint/SuppressedException:
  AllowComments: true
Lint/AmbiguousAssignment: # new in 1.7
  Enabled: true
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true
Lint/AmbiguousRange: # new in 1.19
  Enabled: true
Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: true
Lint/DeprecatedConstants: # new in 1.8
  Enabled: true
Lint/DuplicateBranch: # new in 1.3
  Enabled: true
  IgnoreLiteralBranches: true
  IgnoreConstantBranches: true
Lint/DuplicateMagicComment: # new in 1.37
  Enabled: true
Lint/DuplicateMatchPattern: # new in 1.50
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: true
Lint/EmptyBlock: # new in 1.1
  Enabled: true
Lint/EmptyClass: # new in 1.3
  Enabled: true
Lint/EmptyInPattern: # new in 1.16
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: true
Lint/MixedCaseRange: # new in 1.53
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: true
Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: true
Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: true
Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: true
Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: true
Lint/RedundantRegexpQuantifiers: # new in 1.53
  Enabled: true
Lint/RefinementImportMethods: # new in 1.27
  Enabled: true
Lint/RequireRangeParentheses: # new in 1.32
  Enabled: true
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true
Lint/SymbolConversion: # new in 1.9
  Enabled: true
Lint/ToEnumArguments: # new in 1.1
  Enabled: true
Lint/TripleQuotes: # new in 1.9
  Enabled: true
Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: true
Lint/UselessRescue: # new in 1.43
  Enabled: true
Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true

##
# METRICS COPS
##

Metrics:
  Enabled: false

##
# GEMSPEC COPS
##

Gemspec/DeprecatedAttributeAssignment: # new in 1.30
  Enabled: true
Gemspec/DevelopmentDependencies: # new in 1.44
  Enabled: true
Gemspec/RequireMFA: # new in 1.23
  Enabled: false
Gemspec/OrderedDependencies:
  Enabled: false

##
# BUNDLER COPS
##

Bundler/OrderedGems:
  Enabled: false

##
# RSPEC COPS
##

# documentation can be found in
# http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/<name>
RSpec:
  Enabled: false

RSpec/HookArgument:
  Enabled: true
  EnforcedStyle: each
RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive

##
# CAPYBARA COPS
##

# cant remember installing capybara but whatever
Capybara:
  Enabled: false

##
# FACTORYBOT COPS
##

# cant remember installing factorybot but whatever
FactoryBot:
  Enabled: false

##
# RAKE COPS
##

Rake:
  Enabled: true
