name: Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Run the build and check its size
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2.2"
        bundler-cache: true
    - run: "mkdir -p tmp"
    - name: Inspect the build
      run: bundle exec rake inspect_build
