name: Tests

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:
  tests:
    name: Run tests and linting on Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.2.2'
          - '3.1.4'
          - '3.0.6'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
